"""add_shipping_version_to_snapshot

Revision ID: 1b01423ff433
Revises: 8572f00dc875
Create Date: 2025-12-23 16:22:11.201374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b01423ff433'
down_revision: Union[str, Sequence[str], None] = '8572f00dc875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_pricing_snapshots', sa.Column('shipping_settings_version_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_pricing_snapshots', 'shipping_settings_version_used')
    # ### end Alembic commands ###
