"""Phase 4 shipping and pricing tables

Revision ID: 3e3f85a21bca
Revises: f70dd95feae3
Create Date: 2025-12-22 01:12:05.263873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3f85a21bca'
down_revision: Union[str, Sequence[str], None] = 'f70dd95feae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('weight_per_sq_in_oz', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'weight_per_sq_in_oz')
    # ### end Alembic commands ###
