"""add_shipping_zones

Revision ID: 500380e2dd6c
Revises: 999c3d75543c
Create Date: 2025-12-23 15:51:54.780777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500380e2dd6c'
down_revision: Union[str, Sequence[str], None] = '999c3d75543c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_pricing_history_id'), 'model_pricing_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_pricing_history_id'), table_name='model_pricing_history')
    # ### end Alembic commands ###
