"""Add amazon customization export format

Revision ID: 7ba518abc741
Revises: aa0d56ba8afd
Create Date: 2025-12-26 01:46:29.009597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba518abc741'
down_revision: Union[str, Sequence[str], None] = 'aa0d56ba8afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_settings', sa.Column('amazon_customization_export_format', sa.String(), nullable=False, server_default='xlsx'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_settings', 'amazon_customization_export_format')
    # ### end Alembic commands ###
