"""add header_rows and equipment_type_product_types

Revision ID: 7e65815d3539
Revises: 07b4b191c0db
Create Date: 2025-12-17 20:57:26.844785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e65815d3539'
down_revision: Union[str, Sequence[str], None] = '07b4b191c0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_product_types', sa.Column('header_rows', sa.JSON(), nullable=True))
    op.create_table('equipment_type_product_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('equipment_type_id', sa.Integer(), nullable=False),
        sa.Column('product_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
        sa.ForeignKeyConstraint(['product_type_id'], ['amazon_product_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_type_product_types_id'), 'equipment_type_product_types', ['id'], unique=False)
    op.add_column('product_type_fields', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_type_fields', 'display_name')
    op.drop_index(op.f('ix_equipment_type_product_types_id'), table_name='equipment_type_product_types')
    op.drop_table('equipment_type_product_types')
    op.drop_column('amazon_product_types', 'header_rows')
    # ### end Alembic commands ###
