"""add amazon_customization_template_id to equipment_type

Revision ID: aa0d56ba8afd
Revises: 59987d5abc2b
Create Date: 2025-12-26 00:35:31.397903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0d56ba8afd'
down_revision: Union[str, Sequence[str], None] = '59987d5abc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amazon_customization_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_equip_cust_tmpl', 'amazon_customization_templates', ['amazon_customization_template_id'], ['id'])

    with op.batch_alter_table('shipping_rate_tiers', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_rate_tiers', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'equipment_types', type_='foreignkey')
    op.drop_column('equipment_types', 'amazon_customization_template_id')
    # ### end Alembic commands ###
